#Generated by Fabric Compiler ( version 2022.2-SP1-Lite <build 132640> ) at Mon Oct 23 12:39:08 2023

add_design "C:/Users/15215/Desktop/fpga-race/fpga-race/race/source/main.v"
add_simulation "C:/Users/15215/Desktop/fpga-race/fpga-race/race/source/main.v"
