# ----------------------------------------
# Created on: Mon Oct 23 12:54:46 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/usim"
vmap  adc "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/15215/Desktop/fpga-race/fpga-race/race/pango_sim_libraries/pciegen2"
vlog -work work   \
"C:/Users/15215/Desktop/fpga-race/fpga-race/race/source/main.v" \
"C:/Users/15215/Desktop/fpga-race/fpga-race/race/source/main.v" 

# ----------------------------------------
